/******************************************************************************
 *
 * Module: ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: header file for the ultrasonic driver
 *
 * Author: Esraa Fawzy
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include"std_types.h"

#define ultrasonic_trig_PORT PORTB_ID
#define ultrasonic_trig_PIN PIN5_ID
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * * Description : Function to initialize the ultrasonic driver
 * Initialize the ICU driver.
 *Setup the ICU call back function.
 *Setup the direction for the trigger pin as output pin through the GPIO driver.*/
void Ultrasonic_init(void);

/*Send the Trigger pulse to the ultrasonic*/
void Ultrasonic_Trigger(void);

/*Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void);

/*Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.*/

void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
